import type { Property } from "./types";

/**
 * Realistic placeholder data only — nothing here is fetched from a backend.
 * Replace with a call to lib/api/properties.ts once the FastAPI backend
 * exists; components should not need to change shape when that happens.
 */
export const mockProperties: Property[] = [
  {
    id: "prop_001",
    name: "Skyline Loft at Harbor View",
    address: "482 Harbor View Dr, Unit 12B",
    city: "Austin, TX",
    price: 685000,
    currency: "USD",
    type: "condo",
    status: "available",
    bedrooms: 2,
    bathrooms: 2,
    areaSqm: 118,
    images: [],
    description:
      "Corner-unit condo with floor-to-ceiling windows, private balcony, and dedicated parking. Walking distance to downtown.",
    agentId: "agent_01",
    agentName: "Maria Chen",
    createdAt: "2026-06-02",
  },
  {
    id: "prop_002",
    name: "The Willowbrook Family Home",
    address: "1290 Willowbrook Ln",
    city: "Round Rock, TX",
    price: 512000,
    currency: "USD",
    type: "house",
    status: "under_offer",
    bedrooms: 4,
    bathrooms: 3,
    areaSqm: 245,
    images: [],
    description:
      "Move-in ready two-story home with an open-concept kitchen, fenced backyard, and top-rated school district.",
    agentId: "agent_02",
    agentName: "Daniel Osei",
    createdAt: "2026-05-14",
  },
  {
    id: "prop_003",
    name: "Riverside Modern Townhome",
    address: "77 Riverside Row",
    city: "Austin, TX",
    price: 449900,
    currency: "USD",
    type: "house",
    status: "available",
    bedrooms: 3,
    bathrooms: 2.5,
    areaSqm: 168,
    images: [],
    description:
      "New-construction townhome minutes from the river trail. Energy-efficient build with a rooftop terrace.",
    agentId: "agent_01",
    agentName: "Maria Chen",
    createdAt: "2026-07-01",
  },
  {
    id: "prop_004",
    name: "Cedar Park Garden Apartment",
    address: "3350 Cedar Park Blvd, Apt 4",
    city: "Cedar Park, TX",
    price: 289000,
    currency: "USD",
    type: "apartment",
    status: "available",
    bedrooms: 1,
    bathrooms: 1,
    areaSqm: 74,
    images: [],
    description:
      "Ground-floor apartment with a private garden patio in a quiet, well-maintained community.",
    agentId: "agent_03",
    agentName: "Priya Nair",
    createdAt: "2026-07-18",
  },
  {
    id: "prop_005",
    name: "Downtown Office Suite",
    address: "600 Congress Ave, Suite 900",
    city: "Austin, TX",
    price: 1250000,
    currency: "USD",
    type: "commercial",
    status: "available",
    bedrooms: 0,
    bathrooms: 2,
    areaSqm: 340,
    images: [],
    description:
      "Class-A office suite with skyline views, reception area, and four private offices. Ideal for a growing firm.",
    agentId: "agent_02",
    agentName: "Daniel Osei",
    createdAt: "2026-04-22",
  },
  {
    id: "prop_006",
    name: "Lakeview Estate Lot",
    address: "Lot 14, Lakeview Estates",
    city: "Lakeway, TX",
    price: 375000,
    currency: "USD",
    type: "land",
    status: "off_market",
    bedrooms: 0,
    bathrooms: 0,
    areaSqm: 4046,
    images: [],
    description:
      "One-acre unimproved lot with lake access and approved plans for a custom build.",
    agentId: "agent_03",
    agentName: "Priya Nair",
    createdAt: "2026-03-09",
  },
  {
    id: "prop_007",
    name: "Historic Bungalow on Elm",
    address: "214 Elm St",
    city: "Austin, TX",
    price: 598000,
    currency: "USD",
    type: "house",
    status: "sold",
    bedrooms: 3,
    bathrooms: 2,
    areaSqm: 152,
    images: [],
    description:
      "Beautifully restored 1930s bungalow with original hardwood floors and a modern kitchen renovation.",
    agentId: "agent_01",
    agentName: "Maria Chen",
    createdAt: "2026-02-11",
  },
];
