"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, ArrowUpRight, CheckCircle2, Clock3, FileText, Handshake, Loader2, PhoneCall, Users } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import { FormError } from "@/features/auth/components/form-error";
import { ROLE_LABELS } from "@/features/auth/access";
import { getApiErrorMessage } from "@/lib/api/errors";
import { getRetifyDashboard, type RetifyDashboard, type RetifyDashboardPeriod, type RetifyPerformanceMetrics } from "@/lib/api/organization";
import { cn } from "@/lib/utils";

const PERIODS: { value: RetifyDashboardPeriod; label: string }[] = [{value:"7d",label:"7 días"},{value:"30d",label:"30 días"},{value:"90d",label:"90 días"},{value:"all",label:"Todo"}];
const STATUS_LABELS: Record<string,string> = {draft:"Borrador",new:"Nuevo",reviewing:"En revisión",offer_preparation:"Preparación de oferta",offer_sent:"Oferta enviada",negotiating:"Negociando",accepted:"Aceptado",purchased:"Comprado"};

function Kpi({label,value,detail,icon:Icon,tone="default"}:{label:string;value:string|number;detail:string;icon:typeof Users;tone?:"default"|"warning"|"success"}) {
  return <div className={cn("rounded-2xl border p-4",tone==="warning"&&"border-amber-300/60 bg-amber-50/70 dark:border-amber-500/20 dark:bg-amber-500/5",tone==="success"&&"border-emerald-300/60 bg-emerald-50/70 dark:border-emerald-500/20 dark:bg-emerald-500/5")}><div className="flex items-start justify-between gap-3"><p className="text-xs font-medium uppercase tracking-[0.14em] text-muted-foreground">{label}</p><Icon className="size-4 text-muted-foreground" aria-hidden="true"/></div><p className="mt-3 text-3xl font-semibold tracking-tight">{value}</p><p className="mt-1 text-xs text-muted-foreground">{detail}</p></div>;
}

function AdvisorRow({email,role,active,metrics}:{email:string;role:string;active:boolean;metrics:RetifyPerformanceMetrics}) {
  return <div className="grid gap-3 rounded-xl border bg-background/70 p-4 lg:grid-cols-[minmax(180px,1.4fr)_repeat(5,minmax(76px,0.7fr))] lg:items-center"><div className="min-w-0"><div className="flex items-center gap-2"><p className="truncate text-sm font-medium">{email}</p>{!active&&<Badge variant="outline">Inactivo</Badge>}</div><p className="mt-1 text-xs text-muted-foreground">{ROLE_LABELS[role as keyof typeof ROLE_LABELS]??role}</p></div>{[["Recibidos",metrics.received],["Contactados",metrics.contacted],["Propuestas",metrics.proposals_sent],["Aceptados",metrics.accepted],["Conversión",`${metrics.conversion_rate}%`]].map(([label,value])=><div key={label} className="flex items-center justify-between gap-3 lg:block"><span className="text-xs text-muted-foreground">{label}</span><strong className="block text-sm font-semibold tabular-nums lg:mt-1">{value}</strong></div>)}</div>;
}

export function RetifyCommandCenter() {
  const [period,setPeriod]=useState<RetifyDashboardPeriod>("30d");
  const [advisorId,setAdvisorId]=useState("all");
  const [dashboard,setDashboard]=useState<RetifyDashboard|null>(null);
  const [advisorOptions,setAdvisorOptions]=useState<RetifyDashboard["advisors"]>([]);
  const [error,setError]=useState<string|null>(null);
  const [loading,setLoading]=useState(true);
  useEffect(()=>{let cancelled=false;getRetifyDashboard(period,advisorId==="all"?undefined:advisorId).then(response=>{if(cancelled)return;setLoading(false);if(!response.ok){setError(getApiErrorMessage(response.error));return;}setError(null);setDashboard(response.data);if(advisorId==="all")setAdvisorOptions(response.data.advisors);});return()=>{cancelled=true;};},[period,advisorId]);
  const selectedAdvisor=useMemo(()=>advisorOptions.find(advisor=>advisor.user_id===advisorId),[advisorId,advisorOptions]);
  const metrics=dashboard?.summary;
  const percentage=(value:number,total:number)=>total?`${Math.round(value/total*100)}%`:"0%";
  return <Card className="overflow-hidden border-primary/15 bg-gradient-to-br from-background via-background to-primary/[0.035]"><CardContent className="flex flex-col gap-5 p-5 sm:p-6">
    <div className="flex flex-col justify-between gap-4 xl:flex-row xl:items-end"><div><div className="flex items-center gap-2"><Badge className="border-transparent bg-primary/10 text-primary hover:bg-primary/10">Centro de control</Badge><span className="text-xs text-muted-foreground">Datos reales · solo lectura</span></div><h2 className="mt-3 text-xl font-semibold tracking-tight">Pulso del equipo Retify</h2><p className="mt-1 max-w-2xl text-sm text-muted-foreground">Resultados, carga de trabajo y expedientes que necesitan atención, sin abrir cada ficha.</p></div><div className="flex flex-col gap-2 sm:flex-row"><label className="flex flex-col gap-1 text-xs text-muted-foreground">Asesor<select aria-label="Filtrar resultados por asesor" className="h-9 min-w-56 rounded-lg border bg-background px-3 text-sm text-foreground" value={advisorId} onChange={e=>{setLoading(true);setAdvisorId(e.target.value);}}><option value="all">Todo el equipo</option>{advisorOptions.map(a=><option key={a.user_id} value={a.user_id}>{a.email??"Sin correo"}</option>)}</select></label><label className="flex flex-col gap-1 text-xs text-muted-foreground">Periodo de alta<select aria-label="Filtrar resultados por periodo" className="h-9 rounded-lg border bg-background px-3 text-sm text-foreground" value={period} onChange={e=>{setLoading(true);setPeriod(e.target.value as RetifyDashboardPeriod);}}>{PERIODS.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select></label></div></div>
    {error&&<FormError message={error}/>} {loading&&!dashboard?<div className="flex items-center gap-2 py-12 text-sm text-muted-foreground"><Loader2 className="size-4 animate-spin"/>Cargando resultados…</div>:metrics?<>
      <div className={cn("grid gap-3 sm:grid-cols-2 xl:grid-cols-6",loading&&"opacity-60")}><Kpi label="Recibidos" value={metrics.received} detail={`${metrics.active} siguen activos`} icon={Users}/><Kpi label="Contactados" value={metrics.contacted} detail={`${percentage(metrics.contacted,metrics.received)} de los recibidos`} icon={PhoneCall}/><Kpi label="Sin respuesta" value={metrics.no_answer} detail="Último resultado registrado" icon={Clock3} tone={metrics.no_answer?"warning":"default"}/><Kpi label="Seguimientos vencidos" value={metrics.follow_ups_overdue} detail="Requieren acción inmediata" icon={AlertTriangle} tone={metrics.follow_ups_overdue?"warning":"default"}/><Kpi label="Propuestas" value={metrics.proposals_sent} detail={`${metrics.negotiating} negociando`} icon={FileText}/><Kpi label="Aceptados" value={metrics.accepted} detail={`${metrics.conversion_rate}% de conversión`} icon={CheckCircle2} tone="success"/></div>
      <div className="grid gap-4 xl:grid-cols-[1.35fr_0.65fr]"><section className="rounded-2xl border bg-muted/20 p-4"><div className="mb-3 flex items-center justify-between gap-3"><div><h3 className="text-sm font-semibold">Resultados por asesor</h3><p className="text-xs text-muted-foreground">{selectedAdvisor?.email??"Comparativo del equipo"}</p></div><Badge variant="outline">{dashboard.advisors.length} {dashboard.advisors.length===1?"persona":"personas"}</Badge></div><div className="flex flex-col gap-2">{dashboard.advisors.length?dashboard.advisors.map(a=><AdvisorRow key={a.user_id} email={a.email??"Sin correo"} role={a.role} active={a.is_active} metrics={a.metrics}/>):<p className="rounded-xl border border-dashed p-6 text-center text-sm text-muted-foreground">No hay resultados para este filtro.</p>}</div></section>
      <section className="rounded-2xl border bg-muted/20 p-4"><div className="mb-3 flex items-center justify-between"><div><h3 className="text-sm font-semibold">Necesitan atención</h3><p className="text-xs text-muted-foreground">Ordenados por urgencia</p></div><Badge variant="outline">{dashboard.attention.length}</Badge></div><div className="flex max-h-[390px] flex-col gap-2 overflow-y-auto pr-1">{dashboard.attention.length?dashboard.attention.map(item=><Link key={item.case_id} href={`/leads/renova/${item.case_id}`} className="group rounded-xl border bg-background p-3 transition-colors hover:border-primary/35"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="truncate text-sm font-medium">{item.owner_name}</p><p className="mt-1 text-xs text-muted-foreground">{item.reason}</p></div><ArrowUpRight className="size-4 shrink-0 text-muted-foreground"/></div><div className="mt-2 flex flex-wrap items-center gap-1.5 text-[11px] text-muted-foreground"><Badge variant="outline" className={cn("h-5",item.priority==="urgent"&&"border-red-300 bg-red-50 text-red-700")}>{item.priority==="urgent"?"Urgente":"Alta"}</Badge><span>{STATUS_LABELS[item.status]??item.status}</span><span>·</span><span>{item.advisor_email??"Sin asignar"}</span></div></Link>):<div className="rounded-xl border border-dashed p-6 text-center"><CheckCircle2 className="mx-auto size-5 text-emerald-500"/><p className="mt-2 text-sm font-medium">Sin alertas prioritarias</p></div>}</div></section></div>
      <div className="grid gap-3 sm:grid-cols-3"><div className="rounded-xl border p-3"><Handshake className="size-4 text-muted-foreground"/><p className="mt-2 text-xs text-muted-foreground">Operaciones abiertas</p><p className="text-lg font-semibold">{metrics.operations_open}</p></div><div className="rounded-xl border p-3"><CheckCircle2 className="size-4 text-muted-foreground"/><p className="mt-2 text-xs text-muted-foreground">Operaciones cerradas</p><p className="text-lg font-semibold">{metrics.operations_closed}</p></div><div className="rounded-xl border p-3"><FileText className="size-4 text-muted-foreground"/><p className="mt-2 text-xs text-muted-foreground">Rechazados/cancelados</p><p className="text-lg font-semibold">{metrics.closed+metrics.archived}</p></div></div>
    </>:null}
  </CardContent></Card>;
}
