import type { Appointment } from "./types";

/** Realistic placeholder data only — see features/properties/mock-data.ts. */
export const mockAppointments: Appointment[] = [
  {
    id: "appt_001",
    title: "Viewing — Riverside Modern Townhome",
    date: "2026-09-01",
    time: "10:30",
    durationMinutes: 45,
    leadId: "lead_002",
    leadName: "Aisha Patel",
    propertyId: "prop_003",
    propertyName: "Riverside Modern Townhome",
    type: "viewing",
    status: "confirmed",
    agentId: "agent_01",
    agentName: "Maria Chen",
  },
  {
    id: "appt_002",
    title: "Negotiation call — Skyline Loft",
    date: "2026-09-01",
    time: "14:00",
    durationMinutes: 30,
    leadId: "lead_001",
    leadName: "Jordan Kim",
    propertyId: "prop_001",
    propertyName: "Skyline Loft at Harbor View",
    type: "call",
    status: "scheduled",
    notes: "Discuss counter-offer before end of week.",
    agentId: "agent_01",
    agentName: "Maria Chen",
  },
  {
    id: "appt_003",
    title: "Qualification call",
    date: "2026-09-02",
    time: "09:00",
    durationMinutes: 20,
    leadId: "lead_005",
    leadName: "Ethan Brooks",
    propertyId: "prop_005",
    propertyName: "Downtown Office Suite",
    type: "call",
    status: "scheduled",
    agentId: "agent_02",
    agentName: "Daniel Osei",
  },
  {
    id: "appt_004",
    title: "Viewing — Willowbrook Family Home",
    date: "2026-09-02",
    time: "16:30",
    durationMinutes: 45,
    leadId: "lead_003",
    leadName: "Marcus Webb",
    propertyId: "prop_002",
    propertyName: "The Willowbrook Family Home",
    type: "viewing",
    status: "scheduled",
    agentId: "agent_02",
    agentName: "Daniel Osei",
  },
  {
    id: "appt_005",
    title: "Closing appointment",
    date: "2026-09-04",
    time: "11:00",
    durationMinutes: 60,
    leadId: "lead_006",
    leadName: "Grace Lin",
    propertyId: "prop_007",
    propertyName: "Historic Bungalow on Elm",
    type: "closing",
    status: "confirmed",
    agentId: "agent_01",
    agentName: "Maria Chen",
  },
  {
    id: "appt_006",
    title: "Intro meeting — lot financing options",
    date: "2026-08-29",
    time: "13:15",
    durationMinutes: 30,
    leadId: "lead_008",
    leadName: "Nadia Hussein",
    propertyId: "prop_006",
    propertyName: "Lakeview Estate Lot",
    type: "meeting",
    status: "completed",
    agentId: "agent_03",
    agentName: "Priya Nair",
  },
];
