import type { RenovaCase } from "@/features/renova/types";

/** A fully-filled fictional Renova case as the backend would return it (masks only — never a full NSS / credit number). */
export function makeRenovaCase(overrides: Partial<RenovaCase> = {}): RenovaCase {
  return {
    id: "9f3a2c41-7b1d-4e0a-8c55-0d6e1f2a3b4c",
    organization_id: "org-1",
    assigned_user_id: "user-1",
    created_by_user_id: "user-1",
    entry_date: "2026-09-20",
    source: "whatsapp",
    status: "reviewing",
    archived: false,
    owner_name: "María López",
    owner_phone: "+52 81 5555 0101",
    marital_status: "married_conjugal_partnership",
    spouse_name: "Juan Pérez",
    spouse_phone: "+52 81 5555 0202",
    street_address: "Av. Constitución 123",
    neighborhood: "Centro",
    municipality: "Monterrey",
    postal_code: "64000",
    occupancy_status: "rented",
    dwelling_type: "apartment",
    is_duplex: true,
    floors: 2,
    bathrooms: "2.5",
    bedrooms: 3,
    conditions: "Requiere pintura",
    has_deeds: "yes",
    deeds_holder_name: "María López",
    currency: "MXN",
    final_offer: "950000.00",
    market_value: "1400000.00",
    property_tax_debt: "12000.00",
    property_tax_debt_unit: "mxn",
    other_debt: null,
    water_debt: "800.00",
    electricity_debt: "450.00",
    gas_debt: null,
    debt_owed_to: "Infonavit",
    owner_expected_amount: "1100000.00",
    total_debt: "13250.00",
    sale_reason: "Se muda de ciudad",
    key_questions: null,
    general_situation: "Dueña con prisa por vender",
    notes: "Contacto por WhatsApp",
    nss_masked: "•••••••4455",
    credit_number_masked: "••••••9911",
    has_nss: true,
    has_credit_number: true,
    created_at: "2026-09-20T12:00:00Z",
    updated_at: "2026-09-21T15:30:00Z",
    ...overrides,
  };
}
