import type { Deal } from "./types";

/** Realistic placeholder data only — see features/properties/mock-data.ts. */
export const mockDeals: Deal[] = [
  {
    id: "deal_001",
    leadId: "lead_005",
    leadName: "Ethan Brooks",
    propertyId: "prop_005",
    propertyName: "Downtown Office Suite",
    stage: "new",
    value: 1250000,
    currency: "USD",
    probability: 10,
    expectedCloseDate: "2026-11-15",
    agentId: "agent_02",
    agentName: "Daniel Osei",
    updatedAt: "2026-08-29",
  },
  {
    id: "deal_002",
    leadId: "lead_004",
    leadName: "Sofia Ramirez",
    propertyId: "prop_004",
    propertyName: "Cedar Park Garden Apartment",
    stage: "contacted",
    value: 289000,
    currency: "USD",
    probability: 20,
    expectedCloseDate: "2026-10-20",
    agentId: "agent_03",
    agentName: "Priya Nair",
    updatedAt: "2026-08-27",
  },
  {
    id: "deal_003",
    leadId: "lead_003",
    leadName: "Marcus Webb",
    propertyId: "prop_002",
    propertyName: "The Willowbrook Family Home",
    stage: "qualified",
    value: 512000,
    currency: "USD",
    probability: 35,
    expectedCloseDate: "2026-10-05",
    agentId: "agent_02",
    agentName: "Daniel Osei",
    updatedAt: "2026-08-28",
  },
  {
    id: "deal_004",
    leadId: "lead_008",
    leadName: "Nadia Hussein",
    propertyId: "prop_006",
    propertyName: "Lakeview Estate Lot",
    stage: "qualified",
    value: 375000,
    currency: "USD",
    probability: 30,
    expectedCloseDate: "2026-10-25",
    agentId: "agent_03",
    agentName: "Priya Nair",
    updatedAt: "2026-08-26",
  },
  {
    id: "deal_005",
    leadId: "lead_002",
    leadName: "Aisha Patel",
    propertyId: "prop_003",
    propertyName: "Riverside Modern Townhome",
    stage: "viewing_scheduled",
    value: 449900,
    currency: "USD",
    probability: 50,
    expectedCloseDate: "2026-09-30",
    agentId: "agent_01",
    agentName: "Maria Chen",
    updatedAt: "2026-08-30",
  },
  {
    id: "deal_006",
    leadId: "lead_001",
    leadName: "Jordan Kim",
    propertyId: "prop_001",
    propertyName: "Skyline Loft at Harbor View",
    stage: "negotiation",
    value: 685000,
    currency: "USD",
    probability: 75,
    expectedCloseDate: "2026-09-18",
    agentId: "agent_01",
    agentName: "Maria Chen",
    updatedAt: "2026-08-31",
  },
  {
    id: "deal_007",
    leadId: "lead_006",
    leadName: "Grace Lin",
    propertyId: "prop_007",
    propertyName: "Historic Bungalow on Elm",
    stage: "won",
    value: 598000,
    currency: "USD",
    probability: 100,
    expectedCloseDate: "2026-08-15",
    agentId: "agent_01",
    agentName: "Maria Chen",
    updatedAt: "2026-08-15",
  },
  {
    id: "deal_008",
    leadId: "lead_007",
    leadName: "Owen Fischer",
    propertyId: null,
    propertyName: null,
    stage: "lost",
    value: 325000,
    currency: "USD",
    probability: 0,
    expectedCloseDate: "2026-08-01",
    agentId: "agent_03",
    agentName: "Priya Nair",
    updatedAt: "2026-08-01",
  },
];
